modLoader="javafml"
loaderVersion="[32,)"
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/ToolBelt/issues"
displayURL="https://github.com/gigaherz/ToolBelt"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"
license="BSD (3 clause)"

[[mods]]
modId="toolbelt"
version="${file.jarVersion}"
displayName="Tool Belt"
description='''
Declutter your inventory of tools
'''

[[dependencies.toolbelt]]
   modId="forge"
   mandatory=true
   versionRange="[33.0.5,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.2,1.17)"
   ordering="NONE"
   side="BOTH"