modLoader="javafml"
loaderVersion="[27,)"
#updateJSONURL="http://myurl.me/"
issueTrackerURL="https://github.com/gigaherz/ToolBelt/issues"
displayURL="https://github.com/gigaherz/ToolBelt"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[mods]]
modId="toolbelt"
version="${version}"
displayName="Tool Belt"
description='''
Declutter your inventory of tools
'''

[[dependencies.toolbelt]]
   modId="forge"
   mandatory=true
   versionRange="[27.0.12,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.toolbelt]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.14.3,1.15)"
   ordering="NONE"
   side="BOTH"